# Generated by Django 4.2 on 2023-06-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='cvr_url',
        ),
        migrations.AddField(
            model_name='clothes',
            name='product_image',
            field=models.ImageField(default='blank', upload_to='media/images/'),
        ),
    ]
