# Generated by Django 4.2 on 2023-06-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_clothes_cvr_url_clothes_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
