# Generated by Django 4.2 on 2023-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('cvr_url', models.CharField(max_length=2048)),
            ],
        ),
    ]
